camera_ip_info: rtsp://admin:Orbital227@192.168.24.152:3002/0/profile2/media.smp
from_addr: tap.emailer@gmail.com
to_addr:
- troyap111@gmail.com
- sterling.cottam@cobramaster.com
password: shsslnngjsnayfew